
#
# Copyright (C) 2017 DBot
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

weaponBase = '''

--
-- Copyright (C) 2017 DBot
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- Was auto generated by allclass_melee.py

AddCSLuaFile()

BaseClass = baseclass.Get('dbot_tf_melee')

SWEP.Base = 'dbot_tf_melee'
SWEP.Author = 'DBot'
SWEP.Category = 'TF2 {Class}'
SWEP.PrintName = '{Name}'
SWEP.ViewModel = '{Arms}'
SWEP.WorldModel = '{World}'
SWEP.Spawnable = true
SWEP.AdminSpawnable = true
SWEP.AdminOnly = false
SWEP.UseHands = false

SWEP.MissSoundsScript = 'Weapon_{SoundName}.Miss'
SWEP.MissCritSoundsScript = 'Weapon_{SoundName}.MissCrit'
SWEP.HitSoundsScript = 'Weapon_{SoundName}.HitWorld'
SWEP.HitSoundsFleshScript = 'Weapon_{SoundName}.HitFlesh'

SWEP.DrawAnimation = 'melee_allclass_draw'
SWEP.IdleAnimation = 'melee_allclass_idle'
{animsCode}
'''

AnimsAll = '''
SWEP.AttackAnimation = 'melee_allclass_swing_a'
SWEP.AttackAnimationTable = {'melee_allclass_swing_a', 'melee_allclass_swing_b'}
SWEP.AttackAnimationCrit = 'melee_allclass_swing_c'
'''

AnimsOne = '''
SWEP.AttackAnimation = 'melee_allclass_swing'
SWEP.AttackAnimationTable = {'melee_allclass_swing'}
SWEP.AttackAnimationCrit = 'melee_allclass_swing'
'''

Classes = [
    {
        'name': 'SCOUT',
        'hname': 'Scout',
        'iname': 'scout',
        'fname': 'sc',
        'allanims': False,
        'soundname': 'Bat',
        'arms': 'models/weapons/c_models/c_scout_arms.mdl'
    },
    {
        'name': 'MEDIC',
        'hname': 'Medic',
        'iname': 'medic',
        'fname': 'md',
        'allanims': False,
        'soundname': 'BoneSaw',
        'arms': 'models/weapons/c_models/c_medic_arms.mdl'
    },
    {
        'name': 'ENGINEER',
        'hname': 'Engineer',
        'iname': 'engineer',
        'fname': 'en',
        'allanims': False,
        'soundname': 'Wrench',
        'arms': 'models/weapons/c_models/c_engineer_arms.mdl'
    },
    {
        'name': 'DEMO',
        'hname': 'Demoman',
        'iname': 'demoman',
        'fname': 'de',
        'allanims': True,
        'soundname': 'Bottle',
        'arms': 'models/weapons/c_models/c_demo_arms.mdl'
    },
    {
        'name': 'HEAVY',
        'hname': 'Heavy',
        'iname': 'heavy',
        'fname': 'he',
        'allanims': False,
        'soundname': 'Fist',
        'arms': 'models/weapons/c_models/c_heavy_arms.mdl'
    },
    {
        'name': 'PYRO',
        'hname': 'Pyro',
        'iname': 'pyro',
        'fname': 'py',
        'allanims': False,
        'soundname': 'FireAxe',
        'arms': 'models/weapons/c_models/c_pyro_arms.mdl'
    },
    {
        'name': 'SNIPER',
        'hname': 'Sniper',
        'iname': 'sniper',
        'fname': 'sn',
        'allanims': True,
        'soundname': 'Machete',
        'arms': 'models/weapons/c_models/c_sniper_arms.mdl'
    },
    {
        'name': 'SOLDIER',
        'hname': 'Soldier',
        'iname': 'soldier',
        'fname': 'so',
        'allanims': False,
        'soundname': 'Shovel',
        'arms': 'models/weapons/c_models/c_soldier_arms.mdl'
    },
    {
        'name': 'SPY',
        'hname': 'Spy',
        'iname': 'spy',
        'fname': 'sp',
        'allanims': False,
        'soundname': 'Knife',
        'arms': 'models/weapons/c_models/c_spy_arms.mdl'
    }
]

Weapons = [
    {
        'classname': 'memorymaker',
        'name': 'Memory Maker',
        'model': 'models/weapons/c_models/c_8mm_camera/c_8mm_camera.mdl',
        'exclude': ['SPY', 'ENGINEER']
    }
]

for weapon in Weapons:
    for myClass in Classes:
        if myClass['name'] in weapon['exclude']:
            continue
        fil = open('moon/weapons/dbot_tf_{wep}_{iclass}.moon'.format(wep = weapon['classname'], iclass = myClass['fname']), 'w')
        formatted = weaponBase.format(
            Class = myClass['hname'],
            Name = weapon['name'],
            Arms = myClass['arms'],
            World = weapon['model'],
            animsCode = myClass['allanims'] and AnimsAll or AnimsOne,
            SoundName = myClass['soundname']
        )
        fil.write(formatted)
        fil.close()
