local BaseClass = baseclass.Get('dbot_tf_shotgun')
SWEP.Base = 'dbot_tf_shotgun'
SWEP.Author = 'DBot'
SWEP.Category = 'TF2'
SWEP.PrintName = 'Pyro Shotgun'
SWEP.HandsModel = 'models/weapons/c_models/c_pyro_arms.mdl'
SWEP.Spawnable = true
SWEP.AdminSpawnable = true
SWEP.AdminOnly = false
