local BaseClass = baseclass.Get('dbot_tf_shotgun')
SWEP.Base = 'dbot_tf_shotgun'
SWEP.Author = 'DBot'
SWEP.Category = 'TF2'
SWEP.PrintName = 'Soldier Shotgun'
SWEP.ViewModel = 'models/weapons/v_models/v_shotgun_soldier.mdl'
SWEP.WorldModel = 'models/weapons/w_models/w_shotgun.mdl'
SWEP.Spawnable = true
SWEP.AdminSpawnable = true
SWEP.AdminOnly = false
